# Generated by Django 4.2.5 on 2023-09-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='popularity',
        ),
    ]
